name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   couven92
    ref:        refs/heads/msbuild-template
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - task: UseDotNet@2
      displayName:  Use .NET Core SDK version 3.x
      inputs:
        version:    3.x
    common:
      allProjects: |
        [Ss]rc/*/*.csproj
        [Tt]est/*/*.csproj
    independantRuntime:
      arguments:  '-p:NoNetFramework=false'
      pool:
        vmImage:  windows-latest
    windowsRuntime: ${{ variables.null }}
    linuxRuntime: ${{ variables.null }}
    macRuntime: ${{ variables.null }}
- template: templates/msbuild/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    common:
      srcProjects: |
        src/*/*.csproj
        src-msbuild/*/*.csproj
    defaultPlatform: ${{ variables.null }}
    platforms:
    - id:           anycpu
      displayName:  Any CPU
      argValue:     Any CPU
    - id:           arm
      displayName:  ARM
      argValue:     ARM
    - id:           iphone
      displayName:  iPhone
      argValue:     iPhone
    - id:           iphonesimulator
      displayName:  iPhoneSimulator
      argValue:     iPhoneSimulator
    - id:           x64
      displayName:  x64
      argValue:     x64
    - id:           x86
      displayName:  x86
      argValue:     x86
