name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   couven92
variables:
- group:  Couven92.XamarinPlayground.Notes.iOS
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - task: UseDotNet@2
      displayName:  Use .NET Core SDK version 3.x
      inputs:
        version:    3.x
    common:
      allProjects: |
        [Ss]rc/*/*.csproj
        [Tt]est/*/*.csproj
    independantRuntime:
      arguments:  '-p:NoNetFramework=false'
      pool:
        vmImage:  windows-latest
    windowsRuntime: ${{ variables.null }}
    linuxRuntime: ${{ variables.null }}
    macRuntime: ${{ variables.null }}
- template: templates/msbuild/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    common:
      allProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.Android/*.csproj
      srcProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.Android/*.csproj
    publish:
      skip:         true
    test:
      skip:         true
    defaultPlatform:
      id:           android
      displayName:  Android
      condition:    ne(variables['SkipAndroidPlatform'], 'true')
    debugConfiguration:
      displayName:  'MSBuild: Debug'
    releaseConfiguration:
      displayName:  'MSBuild: Release'
- template: templates/msbuild/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    common:
      allProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.UWP/*.csproj
      srcProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.UWP/*.csproj
    pack:
      skip:         true
    publish:
      arguments:    /p:UapAppxPackageBuildMode=CI /p:AppxBundle=Always
    test:
      skip:         true
    defaultPlatform: ${{ variables.null }}
    debugConfiguration:
      displayName:  'MSBuild: Debug'
    releaseConfiguration:
      displayName:  'MSBuild: Release'
    platforms:
    - id:           uwpArm
      displayName:  'UWP: ARM'
      argValue:     ARM
      condition:    and(ne(variables['SkipUwpArmPlatform'], 'true'), ne(variables['SkipUwpPlatforms'], 'true'))
    - id:           uwpx64
      displayName:  'UWP: x64'
      argValue:     x64
      condition:    and(ne(variables['SkipUwpx64Platform'], 'true'), ne(variables['SkipUwpPlatforms'], 'true'))
    - id:           uwpx86
      displayName:  'UWP: x86'
      argValue:     x86
      condition:    and(ne(variables['SkipUwpx86Platform'], 'true'), ne(variables['SkipUwpPlatforms'], 'true'))
- template: templates/msbuild/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - task: InstallAppleCertificate@2
      displayName:  Install Apple Developer Certificate
      inputs:
        certSecureFile: Couven92.XamarinPlayground.Notes.iOS.p12
        certPwd:        '$(Couven92.XamarinPlayground.Notes.iOS.password)'
    defaultPool:
      vmImage:      macOS-latest
    common:
      allProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.iOS/*.csproj
      srcProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.iOS/*.csproj
      addArguments: '/p:Codesignkey="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)"'
    pack:
      skip:         true
    publish:
      arguments:    /p:BuildIpa=true
    test:
      skip:         true
    defaultPlatform:  ${{ variables.null }}
    platforms:
    - id:           iPhone
      displayName:  iPhone
      argValue:     iPhone
      condition:    and(ne(variables['SkipIPhonePlatform'], 'true'), ne(variables['SkipIPhonePlatforms'], 'true'))
    - id:           iPhoneSimulator
      displayName:  iPhone Simulator
      argValue:     iPhoneSimulator
      condition:    and(ne(variables['SkipIPhoneSimulatorPlatform'], 'true'), ne(variables['SkipIPhonePlatforms'], 'true'))
    debugConfiguration:
      displayName:  'MSBuild: Debug'
    releaseConfiguration:
      displayName:  'MSBuild: Release'
