name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   couven92
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - task: UseDotNet@2
      displayName:  Use .NET Core SDK version 3.x
      inputs:
        version:    3.x
    common:
      allProjects: |
        [Ss]rc/*/*.csproj
        [Tt]est/*/*.csproj
    independantRuntime:
      arguments:  '-p:NoNetFramework=false'
      pool:
        vmImage:  windows-latest
    windowsRuntime: ${{ variables.null }}
    linuxRuntime: ${{ variables.null }}
    macRuntime: ${{ variables.null }}
- template: templates/msbuild/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    defaultPlatform: ${{ variables.null }}
    debugConfiguration:
      displayName:  'MSBuild: Debug'
    releaseConfiguration:
      displayName:  'MSBuild: Release'
    platforms:
    - id:           android
      displayName:  Android
      argValue:     Any CPU
      common:
        allProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.Android/*.csproj
        srcProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.Android/*.csproj
      publish:
        skip:         true
      test:
        skip:         true
    - id:           uwpArm
      displayName:  'UWP: ARM'
      argValue:     ARM
      common:
        allProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.UWP/*.csproj
        srcProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.UWP/*.csproj
      pack:
        skip:         true
      test:
        skip:         true
    - id:           uwpX64
      displayName:  'UWP: x64'
      argValue:     x64
      common:
        allProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.UWP/*.csproj
        srcProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.UWP/*.csproj
      pack:
        skip:         true
      test:
        skip:         true
    - id:           uwpX86
      displayName:  'UWP: x86'
      argValue:     x86
      common:
        allProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.UWP/*.csproj
        srcProjects:  src-msbuild/Couven92.XamarinPlayground.Notes.UWP/*.csproj
      pack:
        skip:         true
      test:
        skip:         true
